FG="{foreground}"
BTN_BG="{color0}"
BRIGHT="#{color8.darken(5%)}"
L_BRIGHT="#{color8.darken(3%)}"
DARK="#{color0.lighten(2%)}"
L_DARK="#{color0.lighten(3%)}"
N_FG="{foreground}"
B_FG="{foreground}"
BTN_FG="#{color10.lighten(70%)}"
N_BG="{background}"
WINDOW="{color0}"
SHADOW="#{color0.lighten(5%)}"
SEL_BG="{color10}"
SEL_FG="{color15}"
LINK="{color2}"
V_LINK="{foreground}"
A_BG="#{color8.darken(10%)}"
DEFAULT="{foreground}"
TOOLTIP_BG="{background}"
TOOLTIP_FG="{foreground}"
PLACEHOLDER="{foreground}"

export FG BTN_BG BRIGHT L_BRIGHT DARK L_DARK N_FG B_FG BTN_FG N_BG WINDOW SHADOW SEL_BG SEL_FG LINK V_LINK A_BG DEFAULT TOOLTIP_BG TOOLTIP_FG PLACEHOLDER

D_FG="{color7}"
D_BTN_BG="{color10}"
D_BRIGHT="#{color0.lighten(2%)}"
D_L_BRIGHT="#{color0.lighten(1%)}"
D_DARK="#{color8.darken(5%)}"
D_L_DARK="#{color8.darken(3%)}"
D_N_FG="{color7}"
D_B_FG="{color7}"
D_BTN_FG="#{color10.lighten(70%)}"
D_N_BG="{background}"
D_WINDOW="{background}"
D_SHADOW="{background}"
D_SEL_BG="{color10}"
D_SEL_FG="{color15}"
D_LINK="{color2}"
D_V_LINK="{color7}"
D_A_BG="#{background.lighten(3%)}"
D_DEFAULT="{color7}"
D_TOOLTIP_BG="{background}"
D_TOOLTIP_FG="{color7}"
D_PLACEHOLDER="{color7}"

export D_FG D_BTN_BG D_BRIGHT D_L_BRIGHT D_DARK D_L_DARK D_N_FG D_B_FG D_BTN_FG D_N_BG D_WINDOW D_SHADOW D_SEL_BG D_SEL_FG D_LINK D_V_LINK D_A_BG D_DEFAULT D_TOOLTIP_BG D_TOOLTIP_FG D_PLACEHOLDER
